name: leafguard
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/iconLogo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/about.png
    - assets/model.tflite
    - assets/labels.txt
    - assets/images/banner1.png
    - assets/images/banner2.png
    - assets/images/banner3.png
    - assets/images/LeafLogo.png
    - assets/images/LeafLogoGreen.png
    - assets/images/LeafLogoWhite.png
    - assets/images/Bacterial-Blight.jpg
    - assets/images/leaf-spot-on.jpg
    - assets/images/powdery-mildew.jpg
    - assets/images/root-rot.jpg
    - assets/images/virus.jpg
    - assets/images/Black_Rot.jpg
    - assets/images/Cabbage_Worms.jpg
    - assets/images/Downy_Mildew.jpg
    - assets/images/Early_Blight.jpg
    - assets/images/Fusarium_Wilt.jpg
    - assets/images/Leaf_Spot.jpg
    - assets/images/Powdery_Scab.jpg
    - assets/images/Rust.png
    - assets/images/Tomato_Blight.jpg
    - assets/images/iconLogo.png
    - assets/diseases.json

